name: Scheduled Stop
on:
  schedule:
    # 12:40 PM EST is 16:40 UTC
    - cron: '40 16 * * *' 
  workflow_dispatch: 

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Codespace
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh codespace stop -c super-guide-x5x79v7xwxj92v7gx